### ISSUE TITLE
Minify all uploads

### ISSUE THREAD

**Issue by bates64** [OpenSprites/OpenSprites-next#18]
Every upload should be stripped of unneeded contents and minified before being added to the db.

**Comment by MegaApuTurkUltra** [comment]
We could also attempt to losslessly compress images and sounds :P

**Comment by bates64** [comment]
@MegaApuTurkUltra that's what I meant, lol.

**Comment by MegaApuTurkUltra** [comment]
For scripts, minifying JSON is easy (`JSON.stringify(JSON.parse)`

For images, we can use `imagemin` with the same settings that `gulp-imagemin` uses (lossless compression)

Sounds are tricky though. MP3s we can leave as-is, but I'm not sure how we can losslessly compress WAVs

**Comment by bates64** [comment]
> losslessly compress WAVs

doubt it's possible

**Comment by towerofnix** [comment]
I don't know sound formats but isn't a WAV just a file containing all the raw frequency volumes for every (rate) in a sound?

**Comment by MegaApuTurkUltra** [comment]
Images are now minified with gulp-imagemin's settings
