### ISSUE TITLE
Server crash when signing in

### ISSUE THREAD

**Issue by towerofnix** [OpenSprites/OpenSprites-next#19]
Try to sign in and the server will crash with this message:

```
Error: Can't set headers after they are sent.
```

**Comment by bates64** [comment]
No idea what's causing this; to be brutally honest.

**Comment by plastpappa** [comment]
Accidental semicolon, programmer habit or bad grammar? :package:

**Comment by bates64** [comment]
> Accidental semicolon, programmer habit or bad grammar? :package:

; == ,

**Comment by plastpappa** [comment]
`Uncaught SyntaxError: Unexpected token ==`

**Comment by towerofnix** [comment]
On-topic again, here's the error caught by try/catch in `app.post('/signin')`:

```
[TypeError: user.save is not a function]
```

**Comment by bates64** [comment]
That means... that it didn't connect to the database correctly @liam4. I think.

**Comment by towerofnix** [comment]
``` js
let user = await db.User.find({ username: req.body.username })
// ..
user.online = true
user.save()
```

The rest of the database works fine.. I think my user doesn't exist and it's not responding with the proper error page.

EDIT: weird, yeah, it looks like the database isn't working properly here. Did anything database related change overnight?

**Comment by towerofnix** [comment]
Database stuff probably changed, setting up a new one fixed stuff 📦
