### ISSUE TITLE
Make DMCA page

### ISSUE THREAD

**Issue by towerofnix** [OpenSprites/OpenSprites-next#2]
There's already a markdown file in this repository: https://github.com/OpenSprites/OpenSprites-next/blob/master/DMCA.md

**Comment by towerofnix** [comment]
Here's what I've done:

![DMCA image](https://cloud.githubusercontent.com/assets/9948030/16487769/2f47ce5a-3ea3-11e6-9ec4-b0bf04aa01a5.png)

Also, to @nanalan - the fact that I needed to do nothing to [make it look amazing](http://i.cubeupload.com/iiiegY.png) in a small window is wonderful. :heart:

**Comment by towerofnix** [comment]
Should everything be part of the header? It probably makes more sense to just have the centered text be part of the header.

**Comment by towerofnix** [comment]
DMCA with header more like a header:

![DMCA #2](https://cloud.githubusercontent.com/assets/9948030/16488078/0132407a-3ea5-11e6-87c9-7c3568d309c0.png)

**Comment by jamesd-uk** [comment]
Just to note that I'll probably change the method for submitting DMCA reports. At the moment it goes to the abandoned support desk. I'm thinking about having a form which pings the complaint to a email address..?

**Comment by bates64** [comment]
We'll have to get sendgrid up and running or something then
