### ISSUE TITLE
"You are leaving OpenSprites..." message

### ISSUE THREAD

**Issue by jamesd-uk** [OpenSprites/OpenSprites-next#24]
For Scratch compliance there must be a dialog warning users that they are leaving to a foreign site after they click a link.

**Comment by bates64** [comment]
> For Scratch compliance

wat? All scratch does is force the user to select the link themselves

**Comment by jamesd-uk** [comment]
I know, but as an independent project we are automatically considered less trustworthy by both Scratch and users. This feature should be added to create an extra layer of reassurance for those who might believe that they have a higher chance of encountering a malicious link on here than on Scratch.

**Comment by Arinerron** [comment]
And change youtube links. Links in profiles can be clicked though if I
remember right.

**Comment by bates64** [comment]
Right.

**Comment by Tymewalk** [comment]
Perhaps a dialog that says something like:

> **You are leaving OpenSprites.**
> The link (link) is taking you to a site that isn't part of OpenSprites.
> OpenSprites can not guarantee the safety of these links.
> If you want to continue, click the link above. Otherwise, press your browser's back button.

**Comment by Tymewalk** [comment]
Pseudocode implementation. I'm not sure which file this would go into or if this example is even accurate.

```
if (not regex(linkURL, "/^(http(s|)://|)opensprites.org/")) {
    announceWarning()
} else {
    followLink()
}
```

Checks if the URL begins with "https://opensprites.org", "http://opensprites.org", or just "opensprites.org".

**Comment by MegaApuTurkUltra** [comment]
In old opensprites we had a list of allowed domains that were basically opensprites, scratch, and a few others. We can also use the `<a>` tag or a library to parse URLs instead of rolling our own regex.

**Comment by Tymewalk** [comment]
@MegaApuTurkUltra How about something similar, but instead of blocking URLs, you could just add a warning like this (slightly altered from the one above):

> **You are leaving OpenSprites.**
> The link (link) is taking you to a site that isn't trusted by OpenSprites.
> OpenSprites can not guarantee the safety of these links.
> If you want to continue to this site, click the link above. Otherwise, press your browser's back button to go back to OpenSprites.

The warning could also show examples, and tell users to make sure that they're not being tricked.

**Comment by MegaApuTurkUltra** [comment]
![](http://image.prntscr.com/image/76c81ce9c0fb447eab74a7e67f8a9a1a.png)

:tada:
