### ISSUE TITLE
Make page redirect for YouTube links

### ISSUE THREAD

**Issue by Arinerron** [OpenSprites/OpenSprites-next#25]
Should we put YouTube links in Scratch's frame, or create our own?

**Comment by bates64** [comment]
Scratch - there's no reason to reinvent the wheel

**Comment by Arinerron** [comment]
I agree w/ nanalan. Any thoughts?

**Comment by bates64** [comment]
~~Actually, scratch just uses an iframe - we can do the same.~~

**Comment by Arinerron** [comment]
I mean should we use Scratch's page, or create our own? It isn't really that hard to create our own, cause yep, it's an iframe.

**Comment by MegaApuTurkUltra** [comment]
Redirected to Scratch
