### ISSUE TITLE
Allow sharing/download of .sb2 and .sprite2 files (as collections?)

### ISSUE THREAD

**Issue by bates64** [OpenSprites/OpenSprites-next#28]
See the old opensprites source for an implementation of this. @MegaApuTurkUltra?

**Comment by MegaApuTurkUltra** [comment]
Yep. We should generate them on the server-side because collections could potentially have a lot of assets. There should also be a GUI of which assets to include

**Comment by Arinerron** [comment]
In a zip for collection downloading? Would it have a package list with the resource names followed by their license and author?

**Comment by bates64** [comment]
@Arinerron we can add descriptions and stuff as comments in the sprites within the `sb2` it generates.

**Comment by bates64** [comment]
@MegaApuTurkUltra we need to find a easy-to-install node-based zipper for this, right?

**Comment by MegaApuTurkUltra** [comment]
JSZip works in node afaik - but for performance we might want a native-based module if it's not too annoying to install
