### ISSUE TITLE
README.md is not Windows-friendly

### ISSUE THREAD

**Issue by Arinerron** [OpenSprites/OpenSprites-next#32]
On Windows, it isn't `mkdir`, but instead `md`. Also  the `cd` command contains `/`, but it is `\` on Windows.

Note: My Windows knowledge isn't great (because I don't use Windows), but I'm almost certain the commands won't work on Windows.

**Comment by bates64** [comment]
Derp, sorry; can a windows user - @MegaApuTurkUltra - please fix it? I don't have windows so I wouldn't know.

**Comment by MegaApuTurkUltra** [comment]
Windows doesn't care about forward slash in cd
