### ISSUE TITLE
Is making URLs based on an environment variable a good idea?

### ISSUE THREAD

**Issue by towerofnix** [OpenSprites/OpenSprites-next#34]
``` js
`/${process.env.resources_name.toLowerCase()}/:id`
```

I don't think so. Resources should have one API/URL name, _resources_. We can display it as "stuff" (which is a word I don't like, but that's another issue haha!) but the URL should always be "resource".

**Comment by MegaApuTurkUltra** [comment]
Implementing this. I have client code now that depends on this so it's going to be resources
