### ISSUE TITLE
Every `await` MUST have a try/catch

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites-next#35]
Let's make this iteration of OpenSprites more robust.

I've started implementing some try/catches on certain endpoints

**Comment by MegaApuTurkUltra** [comment]
Even client side awaits need a try/catch. Seriously. Everything needs to have a failure mode :package:

**Comment by bates64** [comment]
Pretty sure this is complete? @MegaApuTurkUltra

**Comment by MegaApuTurkUltra** [comment]
I guess so
