### ISSUE TITLE
Selected text is not visible against headers

### ISSUE THREAD

**Issue by towerofnix** [OpenSprites/OpenSprites-next#4]
For example:

![Selection issue](https://cloud.githubusercontent.com/assets/9948030/16493086/a5634a94-3eba-11e6-81d4-9d7f5d85c306.png)

I have "Privacy Policy (WIP)".."Information we" selected.

![Selection issue #2](https://cloud.githubusercontent.com/assets/9948030/16493119/b95aea20-3eba-11e6-9b40-0e568c74fdc2.png)

But you can't see I have "Privacy Policy (WIP)" selected against the header.

**Comment by bates64** [comment]
![image](https://cloud.githubusercontent.com/assets/9429556/16495456/74ba223e-3ee5-11e6-9ce9-cac45cbeb169.png)

This is a Firefox thing, but I'll invert it.
