### ISSUE TITLE
Collections model

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites-next#42]
We have a Resource model, now we need a Collection model

Collections should contain other collections along with resources, have a list of people with groups (how about owner/manager/curator/subscriber? :shipit:), permission settings for curators and everyone (add projects, remove projects, set title, set about, add curators)

Any other suggestions? Also #40 📦

**Comment by bates64** [comment]
https://github.com/OpenSprites/OpenSprites-next/blob/master/server/db.js#L62

> Collections should contain other collections

Wat?

**Comment by MegaApuTurkUltra** [comment]
Not sure what you're referring to by that line.

I mean that we want some collections to be added to other collections

```
Some collection
 |- a picture
 |- a sound
 |- Another collection
 |   |- a script
 |   \- a picture
 |- another sound
 \- etc
```

so the `resources` field might be better named as `children` or something more generic, where we store refs of `{ kind: String /* Resource | Collection */, item: { type: ObjectId, refPath: 'children.kind' } }` - see #41

**Comment by matthewr6** [comment]
Could you nest a collection in itself?

**Comment by Tymewalk** [comment]
@MegaApuTurkUltra Couldn't that get confusing? What if someone does this:

```
Collection A
 \- Collection B
     \- Collection A
          \- ...
```

Or in words, if I put collection A in collection B, and then collection B in collection A, what happens?

To clarify, the problem is then we have an infinite loop of collections, which could cause huge problems.

**Comment by matthewr6** [comment]
Of course, that'd only be possible if you were using a foreignkey.

**Comment by MegaApuTurkUltra** [comment]
@Tymewalk good point. When adding collections, we need to check if the tree makes sense :package: 

As for problems, since there's no loops in the collections page renderer or thumbnail renderer, there shouldn't be any problems there. The project generator we're eventually going to implement might have some trouble though

**Comment by Tymewalk** [comment]
@MegaApuTurkUltra I was thinking that we could scan subcollections for the root collection, but then users could use A -> B -> C -> A. And even if we go deeper, users can just add another layer.

What if collections couldn't have other collections with collections in them? Or we had "super-collections", which are collections of collections only?

**Comment by MegaApuTurkUltra** [comment]
I think the idea is scan the hierarchy of parent collections before adding a collection to see if it's already there.

**Comment by MegaApuTurkUltra** [comment]
Yay, I've started one. Now to implement all the backend features like listing (paginated) items, adding, removing, checking permissions, adding curators, changing permissions, etc
