### ISSUE TITLE
More animations!

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites-next#43]
We can do better. Being so used to material-ish UIs, OpenSprites "transitions" are currently kind of jarring.

**Comment by bates64** [comment]
I disagree - we're not using material for the majority of the site and many background/color transitions look weird. Try adding `* { transition 300ms }` to the style.

**Comment by MegaApuTurkUltra** [comment]
At the very least we can do some opacity transitions though, right?

Also, currently the way stuff (especially markdown editors) change height all the time and affect the entire page height looks bad imo. Either standardize the height or make a height animation.

**Comment by andrewjcole** [comment]
I agree, I couldn't get past the lack of basic transitions on the buttons.

**Comment by bates64** [comment]
@andrewjcole The buttons look **horrible** with a transition.

**Comment by towerofnix** [comment]
`.subjective.avi`

**Comment by MegaApuTurkUltra** [comment]
I tested in inspect element with a 0.1s 1.05x scale and background fade on the flat buttons and it looks much more smooth than the immediate hover effect we have now.

If we don't agree on whether we need more animations or not we could have it be a user setting

**Comment by andrewjcole** [comment]
Even just a simple fade? I honestly don't know how that could make so much of a difference. 
I've tried `transition: 150ms` and it honestly looks a bit better to me.

**Comment by andrewjcole** [comment]
Also, I think a setting would be a bit redundant. Would users really care to switch something that pointlessly specific?

**Comment by Tymewalk** [comment]
@andrewjcole What if we used a setting that said "Enable fancy animations"? This way users could turn it off if their browser "didn't like it" or can't support it.

**Comment by bates64** [comment]
Meh.
I'll add it for now.

**Comment by MegaApuTurkUltra** [comment]
@andrewjcole the point is to appease the great @nanalan while still being able to have the UI look nice for people that want it (everyone)

**Comment by bates64** [comment]
Is this complete?

**Comment by andrewjcole** [comment]
The non-white buttons still don't have transitions btw.

**Comment by bates64** [comment]
@andrewjcole They aren't supposed to.
