### ISSUE TITLE
Make a forum

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites-next#44]
- Mod an existing node.js forums framework?
- Roll our own?

**Comment by Tymewalk** [comment]
I'm new here, so not sure what restrictions there are, but what's wrong with something like PHPBB or a modded DjangoBB like Scratch uses?

**Comment by MegaApuTurkUltra** [comment]
We need something that runs on node / express

**Comment by Tymewalk** [comment]
@MegaApuTurkUltra OK.

**Comment by Tymewalk** [comment]
What about [NodeBB](http://www.nodebb.org/)? They have [a GitHub repo](https://github.com/NodeBB/NodeBB), so it doesn't look like we'd have to pay for it.

It says it runs on MongoDB.

**Comment by bates64** [comment]
@Tymewalk That doesn't really work for us - as it'll be hard to get our user/pass system running inside NodeBB, let alone on the same port.

---

It's worth us _rolling our own_, to be honest. It doesn't have to be too complicated.

**Comment by Tymewalk** [comment]
@nanalan Ah, OK.

Wasn't there a forum on the old OpenSprites site? Or was that somewhere else?

**Comment by jamesd-uk** [comment]
The forum on the previous site is called EsoTalk. It was pretty neat, but it ran on PHP, and the whole site was basically built around it.

**Comment by bates64** [comment]
>  EsoTalk. It was pretty neat

...we basically had to hack around the sourcecode to get it to work properly for our needs :shipit:

**Comment by jamesd-uk** [comment]
I meant that EsoTalk itself was pretty neat when run as an independent forum only.

**Comment by andrewjcole** [comment]
Personally, the only uses I see for an OpenSprites forum is for requesting resources from other users, and maybe one for site support.

**Comment by bates64** [comment]
@andrewjcole and that could be done through the scratch forum "Requests," right? :package:

**Comment by andrewjcole** [comment]
Yeah, so really, I don't see what we could add in a forum that Scratch doesn't already have.

**Comment by MegaApuTurkUltra** [comment]
I guess you're right....do we really need a forum?

Site support can be done through our existing support thing

**Comment by jamesd-uk** [comment]
I don't feel that we need a forum. It adds extra moderation and maintenance responsibilities.

**Comment by bates64** [comment]
I love how I've commented "we should delete it instead" on issues so far and everybody has agreed
