### ISSUE TITLE
Most Downloaded list is the same as Recently Uploaded

### ISSUE THREAD

**Issue by Tymewalk** [OpenSprites/OpenSprites-next#47]
To reproduce, upload at least 3 items. Download one (so it says downloaded 1 time), but don't download the others.

Check the homepage.

I uploaded the resources in this order (picked some random files I had laying around):
- Antartica flag (not shown)
- Aland flag
- Other flag with eagle on it
- Letter "A"
- Milk
- Chinese character

Then I downloaded the milk, Aland and Antartica flags.

Here is the "Most Downloaded" list:
![](http://u.cubeupload.com/Tymewalk/openspritesdownloadl.png)

Notice that the Antartica flag is missing, and the others are in the order I uploaded them in.

It's not just reversed, either - if it was the milk would be next to the Aland flag.

**Comment by bates64** [comment]
Awesome - thanks for the bug report! Come check out [the gitter room](https://gitter.im/OpenSprites/OpenSprites-next) sometime soon @Tymewalk

**Comment by bates64** [comment]
Interestingly it doesn't look like there's anything in the code that could be causing this...

**Comment by Tymewalk** [comment]
@nanalan Could you point me to where exactly this list is generated? You may have copy-pasted and overlooked changing a key to sort by. (Or I may just be the only one who does that :stuck_out_tongue:)

**Comment by MegaApuTurkUltra** [comment]
here: https://github.com/OpenSprites/OpenSprites-next/blob/077c55ff7e680bfb97f34b76d927dcdda9006479/server/main.js#L938

Shouldn't it be downloaded -1 though? 📦

**Comment by Tymewalk** [comment]
@MegaApuTurkUltra Nice, thanks.

**Comment by MegaApuTurkUltra** [comment]
Seems like I've fixed this by changing that line (judging by the fact that @nanalan's osdev now has the correct order 📦 )

**Comment by Tymewalk** [comment]
I just tested and confirmed that this worked.

**Comment by Tymewalk** [comment]
Can someone re-open this?

This did not fix it, now it just displays the recent list in reverse order.

Here are the steps I took afterwards:
- Pulled OpenSprites from master
- Ran `npm run build`
- Ran `npm start` and went to `localhost:3000`
- Uploaded 4 assets in the following order: Avatar, Dancer, Me, Smiley
- Downloaded Dancer (confirmed it said downloaded 1 time)
- Went to the homepage

![](http://u.cubeupload.com/Tymewalk/opensprstillnotworki.png)

Avatar (which was the only thing uploaded before Dancer) is at the front of the list.

I tested uploading them at the same time, on different pages, and with different files, but no luck.

**Comment by MegaApuTurkUltra** [comment]
hmm, did you try CTRL-F5?

**Comment by Tymewalk** [comment]
@MegaApuTurkUltra Yes. I even tried uploading a new resource from a different account (which confirms it's not sorting alphabetically for whatever reason), and restarting npm.

**Comment by MegaApuTurkUltra** [comment]
Ok _now_ it's fixed

**Comment by Tymewalk** [comment]
![](http://u.cubeupload.com/Tymewalk/osdloadworksnow.png)
Confirmation picture. Nothing else was downloaded, I uploaded the flag to test afterwards.
