### ISSUE TITLE
Make Terms of Service page

### ISSUE THREAD

**Issue by towerofnix** [OpenSprites/OpenSprites-next#5]
Anything in the actual Terms of Service that needs to be changed?

**Comment by jamesd-uk** [comment]
Not really. A few minor tweaks and it should be good to go.

**Comment by towerofnix** [comment]
Done, I think:

![TOS demo](https://cloud.githubusercontent.com/assets/9948030/16494498/e8415fae-3ebf-11e6-91aa-2e3c886f6c66.png)
[Small demo](https://cloud.githubusercontent.com/assets/9948030/16494499/e8416666-3ebf-11e6-916c-11e58b8d1811.png) (too long to sensibly embed in issue)

**Comment by jamesd-uk** [comment]
I actually revised that policy here: https://github.com/OpenSprites/OpenSprites-next/blob/master/DMCA.md
