### ISSUE TITLE
Delete EXIF data

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites-next#54]
The privacy policy says

> All images uploaded to OpenSprites have their metadata deleted immediately

We should actually do that if we're not already (server side would be preferred). [This](https://github.com/hMatoba/piexifjs) is a package that looks like it can do the job without any external dependencies.

**Comment by Tymewalk** [comment]
That tool looks like it only supports JPEGs.

**Comment by MegaApuTurkUltra** [comment]
Only JPEGs have EXIF data to delete 📦

**Comment by Tymewalk** [comment]
@MegaApuTurkUltra Oh, that makes more sense.

**Comment by Tymewalk** [comment]
Pseudocode example:

```
var onUpload = function() {
    ...
    if (file.type == "JPEG") {
        file = piexif.remove(file)
    }
    ...
}
```

**Comment by Tymewalk** [comment]
#55 was merged, so this can be closed.
