### ISSUE TITLE
IE material icons not showing up

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites-next#57]
Material icons do not show up in IE11. I've tried everything, but can't seem to get them to load. We might need to load the icon fonts locally as per [this](http://stackoverflow.com/a/32628649).

**Comment by MegaApuTurkUltra** [comment]
Just detect the IE user agent and don't set the no cache header?

**Comment by bates64** [comment]
For the record - I don't have a copy of Windows anymore, let alone Internet Explorer :package:

**Comment by andrewjcole** [comment]
IE virtual machines. :+1:

**Comment by bates64** [comment]
@andrewjcole ...also can't be bothered :shipit:

**Comment by MegaApuTurkUltra** [comment]
IE doesn't support stacking fonts, it seems. You need to replace all the instances of icons with HTML escape codes for the characters. Super annoying. IE users can live without icons I guess

**Comment by andrewjcole** [comment]
Either that, or I could go against my gut and use images as a fallback.
