### ISSUE TITLE
Anybody's collection descriptions are editable even when logged out

### ISSUE THREAD

**Issue by towerofnix** [OpenSprites/OpenSprites-next#58]
The image describes well enough:

![Image](https://cloud.githubusercontent.com/assets/9948030/16768051/ef429dc4-4818-11e6-9e50-2ca9afe09534.png)

Edit: **Saves on backend as well!** http://alex.bates.is:3000/collections/577eb366a1ac264208bda2df (and do note I was logged out when editing that, not in an admin account or anything)

**Comment by towerofnix** [comment]
Security tag fits, right?

**Comment by MegaApuTurkUltra** [comment]
I'm getting a 403 forbidden [as intended](https://github.com/OpenSprites/OpenSprites-next/blob/master/server/main.js#L625-627)

**Comment by MegaApuTurkUltra** [comment]
I'm getting a 403 forbidden [as intended](https://github.com/OpenSprites/OpenSprites-next/blob/master/server/main.js#L679-681)

**Comment by MegaApuTurkUltra** [comment]
Now for the frontend issue

**Comment by MegaApuTurkUltra** [comment]
github...

**Comment by MegaApuTurkUltra** [comment]
Yay solved 🎉 

With osdev that was extremely painful to debug. @nanalan can we has server console plx? 📦

**Comment by bates64** [comment]
@MegaApuTurkUltra meh

**Comment by towerofnix** [comment]
`/admin/consolelog` would be nice!

**Comment by andrewjcole** [comment]
Wait, does that mean you can't edit your own anymore? Because I'm unable to.

**Comment by MegaApuTurkUltra** [comment]
dangit

**Comment by MegaApuTurkUltra** [comment]
Yay, it's because I forgot another `await`
