### ISSUE TITLE
Have a "backpack"

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites-next#61]
We should have our own backpack that people can temporarily store collections and resources in.

It should have easy "add all to collection" and "download all" buttons :package: 

We can also try using the FileSystem API for more swag (API support across browsers is patchy though)

**Comment by rumanti** [comment]
Does "backpack" have its own features? 

I probably misunderstood, but I don't see much difference between this idea and collections. In Scratch, the difference between backpack and studio is significant, but this is OpenSprites. You still have to create a new, "special" collection just for backpack, but after that, it _should be_ quick and easy.

PS: Is [this](http://www.html5rocks.com/en/tutorials/file/filesystem/) the API you were talking about?

**Comment by bates64** [comment]
@Rumanti Not really, except how you see it...

~~Essentially, it's your own - private - collection that is hidden from view normally~~, and I'm assuming at the bottom right of the page(?), like Google Fonts, where you drag resources you want to download; then you press the download button to download all of them.

~~It's much more streamlined than just a collection.~~

**Comment by jamesd-uk** [comment]
Basically like the 'shopping cart' on Amazon, but instead of purchasing the items at the end of your session, you download them.

**Comment by MegaApuTurkUltra** [comment]
> Basically like the 'shopping cart' on Amazon, but instead of purchasing the items at the end of your session, you download them.

Yeah that's how I imagined it

It should also use localStorage event handlers to update across tabs :package: 

And we could integrate it with the Scratch editor, pixie, and tosh :package:

**Comment by rumanti** [comment]
I see. I feel ignorant now :P

^ btw love the idea of integrating OS with tosh, pixie, and more

**Comment by bates64** [comment]
> And we could integrate it with the Scratch editor, pixie, and tosh

How'd we do that? Magic? :shipit:

**Comment by bates64** [comment]
If we use localStorage to handle it, we won't have to make a hidden collection, too :D

**Comment by MegaApuTurkUltra** [comment]
> How'd we do that? Magic?

For Scratch we load the swf with a param for the sb2 file to open (`post` `/collections/download` with list of items, it gives you back the ID of a cached sb2, open a copy of the Scratch SWF with `get` `/collections/download/id` - then there might some fiddling required to get it to open in editor mode :package: - we'll have to explicitly tell people that they must use file > download to computer to save their edits though)

For pixie and tosh we probably need to do some modding :package:
