### ISSUE TITLE
Script uploads / drag and drop on the upload page

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites-next#62]
Because these kind of go together

Old opensprites allowed you to drag a project or sprite onto the download page, and then it would expand out all the assets and scripts

**Comment by bates64** [comment]
Don't have a "drop here" though, only when hovering an object over that area. Because that annoyed me :package:

**Comment by MegaApuTurkUltra** [comment]
Yay the share page now extracts costumes and sounds from project files.

Should we have an "upload from Scratch URL" option? :shipit:

**Comment by bates64** [comment]
@MegaApuTurkUltra Perhaps when people join allow them to import over projects and backpack items from Scratch as resources

_edit: if plausible_

**Comment by MegaApuTurkUltra** [comment]
Welp, that's going to be difficult

**Comment by MegaApuTurkUltra** [comment]
Done
