### ISSUE TITLE
Salted passwords

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites-next#64]
This is Scratch we're talking about here. There are going to be common passwords.

We could even salt by using shortid :package: 

``` js
let salt = shortid()
let user = new db.User({
  email: req.body.email,
  username: req.body.username,
  salt,
  password: await bcrypt.hash(salt + req.body.password, 12),
  joined: Date.now()
})

// ...

await bcrypt.compare(user[0].salt + req.body.password, user[0].password)
```

**Comment by MegaApuTurkUltra** [comment]
Looks like I didn't read the manual here :P

**Comment by bates64** [comment]
:facepalm:

---

EDITED by [FACEPALMBOT 9000](https://github.com/liam4):

![](http://www.bluehogreport.com/wp-content/uploads/facepalm.jpg)

&lt;end of edit&gt;
