### ISSUE TITLE
Make GUI on Collections & Backpack simpler

### ISSUE THREAD

**Issue by bates64** [OpenSprites/OpenSprites-next#66]
We need to be able to allow 7yo kids to use this :package: 
Checkboxes and stuff are complicated for the average Scratcher.

**Comment by MegaApuTurkUltra** [comment]
Any specific tips?

Without checkboxes how are people going to pick items to download / add / remove / organize?

**Comment by bates64** [comment]
How about drag to add, download all only, drag away to remove, drag to organize.

Bam.

**Comment by MegaApuTurkUltra** [comment]
Drag one by one? Or are we going to have ctrl/shift click?

We should have ctrl/shift click 📦

**Comment by bates64** [comment]
both :shipit:

...if you can be bothered to implement it

**Comment by MegaApuTurkUltra** [comment]
Implemented for backpack (:tada:)
There are also button labels for the backpack now

How do you like it? 📦

**Comment by MegaApuTurkUltra** [comment]
Yay collections now have the same feel and I added button labels

**Comment by MegaApuTurkUltra** [comment]
The os-select color was chosen a bit arbitrarily though. Somebody who can color pls change 📦
