### ISSUE TITLE
IE Compatibility 

### ISSUE THREAD

**Issue by andrewjcole** [OpenSprites/OpenSprites-next#67]
IE compatibility for at least IE11. Likely for post-release.

**Comment by MegaApuTurkUltra** [comment]
For now how about we have a dialog letting people know stuff isn't going to work?

Or make IE = mobile? :shipit:

**Comment by andrewjcole** [comment]
At least for CSS, I've got it looking how it should in IE11. Still some things like messages and backpack that need fixing.

**Comment by bates64** [comment]
@andrewjcole the backpack style will probably change anyway

**Comment by bates64** [comment]
This should be split into multiple issues :smile:

**Comment by andrewjcole** [comment]
Yeah, that's why we have the label. :stuck_out_tongue_winking_eye:

**Comment by bates64** [comment]
wo0t, 50 issues closed :shipit:
