### ISSUE TITLE
CSRF on DELETE requests

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites-next#68]
I can't for the life of me avoid hitting csrf errors when sending a DELETE request via axios. I've tried adding the header, adding the csrf field to the body, and even doing both. As soon as I change it to a POST request, everything's fine

`POST /collections/:id/items/delete` is really bugging me. I'd like to be able to do DELETEs :package:

Anyone know why this is happening?

**Comment by bates64** [comment]
Nope. https://github.com/expressjs/csurf

**Comment by MegaApuTurkUltra** [comment]
I guess I should pull out fiddler and see if it's axios or csurf that's causing the problem

**Comment by MegaApuTurkUltra** [comment]
Axios explicitly ignores request bodies on DELETE requests. I guess this can't be fixed
