### ISSUE TITLE
Implement resource uploading and sharing

### ISSUE THREAD

**Issue by towerofnix** [OpenSprites/OpenSprites-next#7]
Because this is OpenSprites, riiiight?

Will need a backend and a frontend.

**Comment by towerofnix** [comment]
Demos:

Large screen:

![Screen large](https://cloud.githubusercontent.com/assets/9948030/16505661/682fa1ce-3ef4-11e6-9b9a-c67c127b6c6e.png)

Medium screen:

![Screen medium](https://cloud.githubusercontent.com/assets/9948030/16505663/683257de-3ef4-11e6-8442-7d8f86623196.png)

Small screen:

![Screen small](https://cloud.githubusercontent.com/assets/9948030/16505662/68310f3c-3ef4-11e6-9ed7-a4bd8fe40aa6.png)

Only frontend is implemented at the moment.

@nanalan for a separate new issue.. but the header and footer could have some work done for responsiveness on smaller screens.

**Comment by matthewr6** [comment]
Isn't this basically "make OpenSprites"?  (besides user account stuff, of course) :P

**Comment by bates64** [comment]
@liam4 please push those demos
