### ISSUE TITLE
Confirm <head> tag ommital works on IE11

### ISSUE THREAD

**Issue by towerofnix** [OpenSprites/OpenSprites-next#70]
See [/public/views/layouts/main.hbs](https://github.com/OpenSprites/OpenSprites-next/blob/master/public/views/layouts/main.hbs) - it would probably take about five seconds to add `<head>` and `</head>`.

**Comment by bates64** [comment]
**Still valid** under HTML5 and is cleaner imo

**Comment by MegaApuTurkUltra** [comment]
But does IE11 like it?

**Comment by towerofnix** [comment]
`.subjective.avi`

"Is cleaner" is pretty vague. Old browsers aren't going to appreciate not having the `<head>` tag, I imagine.

**Comment by MegaApuTurkUltra** [comment]
The invalid label, by the way, isn't for your opinions. If the issue is subjective, please use the discussion tag

**Comment by MegaApuTurkUltra** [comment]
Can we confirm that IE11 is OK with it? Until then I'd rather keep this issue open

**Comment by bates64** [comment]
Fairly sure it does - browsers always render something, even if the input is dodgy - have you _ever_ seen a webpage that cannot load because of malformed html?

Anyway, this is IE we're talking about.

**Comment by andrewjcole** [comment]
IE11 is automatically separating the `<head>` and `<body>` elements and there are no errors in the console, so it can definitely handle it. Separating the head and body in their tags is more of a practice than anything. 

If everyone does vote to have the `<head>` added, I don't see a problem with it being there. It doesn't get in the way or matter much in the long run.

EDIT: Just thought I'd note that it is completely valid HTML. https://validator.w3.org/nu/?doc=http%3A%2F%2Fosdev.tk%2F

**Comment by bates64** [comment]
>  Just thought I'd note that it is completely valid HTML. https://validator.w3.org/nu/?doc=http%3A%2F%2Fosdev.tk%2F
> 
> **Still valid** under HTML5

There you go :package:

**Comment by andrewjcole** [comment]
I'm pretty sure IE9+ (at least) should be fine with no head, and it's unlikely that we'll ever target any older versions, especially since Scratch supports IE9+.

**Comment by andrewjcole** [comment]
Closed because the name of the issue was "Confirm <head>tag ommital works on IE11", and it does.
