### ISSUE TITLE
GitHub usernames are misaligned on About page

### ISSUE THREAD

**Issue by towerofnix** [OpenSprites/OpenSprites-next#74]
In the team section:

![Ew](https://cloud.githubusercontent.com/assets/9948030/16988440/d155ee52-4e66-11e6-8bdf-24911d5e739e.png)

**Comment by bates64** [comment]
We have an about page? :package:

**Comment by towerofnix** [comment]
http://osdev.tk/about :package:

**Comment by MegaApuTurkUltra** [comment]
Yeah I just threw it together without bothering with styling because I noticed that "Made with :heart: by the OpenSprites team" linked to a 404 📦

**Comment by bates64** [comment]
Perhaps link to their opensprites accounts and images instead

**Comment by andrewjcole** [comment]
There could be links to Scratch accounts too.
