### ISSUE TITLE
Footer isn't connected to bottom of the page

### ISSUE THREAD

**Issue by towerofnix** [OpenSprites/OpenSprites-next#76]
![Ew](https://cloud.githubusercontent.com/assets/9948030/16988639/73231f5c-4e67-11e6-974b-7fd16434bb84.png)

In my opinion it would be better if the footer were fixed to the bottom of the page.

As usual, [flexbox fixes it](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/)..

**Comment by MegaApuTurkUltra** [comment]
What page is this @liam4 ?
