### ISSUE TITLE
Remove "Edit X" buttons

### ISSUE THREAD

**Issue by towerofnix** [OpenSprites/OpenSprites-next#78]
![Ew](https://cloud.githubusercontent.com/assets/9948030/16988953/94d77cdc-4e68-11e6-8759-5d1e95e21ef0.png)

It's right beside "shared". Shouldn't it be to the right of "about"? Also, you can see that the bottom text of "edit about me" is just above the top of "shared". I would think that the (vertical) middle of both texts would be on the same line.

**Comment by MegaApuTurkUltra** [comment]
Screenshot pls? Perhaps what you think is the right spot?

**Comment by towerofnix** [comment]
> (tfw enter submits issue)

Haven't finished writing it lol.

**Comment by towerofnix** [comment]
Okay, finished writing! Thanks GitHub.

**Comment by bates64** [comment]
I'm not even sure we should have "Edit xxx" buttons in the first place.
We have the style scratch uses already - a textarea.

**Comment by andrewjcole** [comment]
Yeah, the button just adds clutter.

**Comment by MegaApuTurkUltra** [comment]
And they're a pain to style for, and add elements around (since they float - `div clear:both`s everywhere) 

+1 for removing it

**Comment by jamesd-uk** [comment]
> +1 for removing it

**Comment by bates64** [comment]
Remove it is

**Comment by MegaApuTurkUltra** [comment]
Done
