### ISSUE TITLE
Use cubeupload/other Scratch-supported image uploading service for downloads

### ISSUE THREAD

**Issue by bates64** [OpenSprites/OpenSprites-next#81]
Currently, Scratch has not whitelisted OpenSprites as an image host - let's resort to using [nightmare](https://npmjs.com/nightmare)[-upload](https://npmjs.com/nightmare-upload)!

**Comment by MegaApuTurkUltra** [comment]
Let's make sure we don't get in trouble for this though

**Comment by MegaApuTurkUltra** [comment]
Cubeuploading works

**Comment by towerofnix** [comment]
<obligatory "what about tinypic?">

**Comment by bates64** [comment]
tinypic has captcha @liam4

**Comment by jamesd-uk** [comment]
Just to note:

This should only be a temporary solution. Once the site has been beta and penetration tested, I'll get in touch with the ST about the possibility of whitelisting.

**Comment by bates64** [comment]
Another note:

CubeUpload **does not support SVG** uploads. This means that until the ST whitelist us, people with SVG image uploads (possibly the most common upload type?) won't be able to use `[img]uploaded.svg[/img]` on the forums :disappointed:

**Comment by MegaApuTurkUltra** [comment]
^ discovered that the hard way. node-canvas anyone? :shipit:
