### ISSUE TITLE
Upload from Scratch (URL)

### ISSUE THREAD

**Issue by towerofnix** [OpenSprites/OpenSprites-next#82]
https://github.com/OpenSprites/OpenSprites-next/issues/62#issuecomment-235080852

> Should we have an "upload from Scratch URL" option? :shipit:

All ideas belong in an issue. :)

@MegaApuTurkUltra

**Comment by bates64** [comment]
I feel like having an "upload from scratch url" input present at all times **could be clutter**...

Even so, we could implement this as, like, a button in the _Chrome/FF Extension_ to appear on actual scratch project pages?

**Comment by MegaApuTurkUltra** [comment]
Done

![](http://image.prntscr.com/image/f5a9fcea8b1140ae890bfc2f257f8401.png)
