### ISSUE TITLE
Optimize collection item loading

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [OpenSprites/OpenSprites-next#89]
- limit the number on profile pages
- paginate or infinite scroll on collections

Stuff is getting a bit slow on my cloud9 instance 📦

**Comment by bates64** [comment]
We can probably borrow some of the code used in the admin list.

**Comment by MegaApuTurkUltra** [comment]
Yay after limiting the number of items on profile pages to 10 (click `more...` for the full list) it's a lot faster 📦

**Comment by MegaApuTurkUltra** [comment]
Collections backend has support for pagination -- now to do frontend

I'll probably do a "load more" button like Scratch. It's annoying to get pushed away from the footer with infinite scroll 📦
