### ISSUE TITLE
Make "top downloaded" section

### ISSUE THREAD

**Issue by towerofnix** [OpenSprites/OpenSprites-next#9]
A row on homepage, possibly with a dedicated page. It'll need there to be a `downloads` field on resource objects.

**Comment by MegaApuTurkUltra** [comment]
Guys let's also make a "Top Kek" section :package:

**Comment by bates64** [comment]
@MegaApuTurkUltra that can be like 1.4's "random projects" section!

**Comment by jamesd-uk** [comment]
Perhaps we could use that as a bug bounty Easter egg. :P

**Comment by Arinerron** [comment]
Or Konami code easter egg :P
